### ISSUE TITLE
Quickstart throws error

### ISSUE THREAD

**Issue by aymuos15** [mazurowski-lab/intrinsic-properties#1]
```
/home/soumya/anaconda3/envs/medicalmnist/bin/python /home/soumya/alien/intrinsic-properties/test.py
/home/soumya/alien/intrinsic-properties/datasetproperties.py:25: SyntaxWarning: invalid escape sequence '\h'
  """
Files already downloaded and verified
computing dataset label sharpness: 100%|████████| 2/2 [00:00<00:00,  2.41it/s]
Traceback (most recent call last):
  File "/home/soumya/alien/intrinsic-properties/test.py", line 16, in <module>
    datadim = compute_intrinsic_datadim(dataset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soumya/alien/intrinsic-properties/datasetproperties.py", line 96, in compute_intrinsic_datadim
    return estimate_intrinsic_dim(dataset, dataset_name, estimator, batchsize=estimator_batchsize, hyperparam_k=hyperparam_k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soumya/alien/intrinsic-properties/src/dimensionality.py", line 20, in estimate_intrinsic_dim
    from main import run_mle, run_geomle, run_twonn
ModuleNotFoundError: No module named 'main'
```

Where is run_mle, run_geomle, run_twonn ?

I have followed the exact steps mentioned in the quickstart.

Thank you.

**Comment by nickk124** [comment]
Hi, I'm happy to help debug!

Those functions are from `main.py` in the https://github.com/ppope/dimensions repository that you cloned in the quickstart, and currently they are imported into our code in a way that **requires you to run your script from the base directory of this codebase** (see https://github.com/mazurowski-lab/intrinsic-properties/blob/99616ac5bcfb2c16b56c30b7f6be9d55c3d4969c/src/dimensionality.py#L18). So in your case, running
```
cd /home/soumya/alien/intrinsic-properties/
/home/soumya/anaconda3/envs/medicalmnist/bin/python test.py

```
should work. Please let me know if it doesn't!

**Comment by aymuos15** [comment]
Fantastic!

I might have misplaced something during the installation yesterday. 

Thank you so much for the quick reply and amazing paper. Thoroughly enjoyed reading it :)
