### ISSUE TITLE
Quickstart throws error and advice.

### ISSUE THREAD

**Issue by sakaili** [mazurowski-lab/intrinsic-properties#2]
1.Quick start error:
When I run test.py, ‘label sharpness=inf’ appears. I think this may be caused by a potential division by zero operation. So I modified the code.
From:
https://github.com/mazurowski-lab/intrinsic-properties/blob/8749459c28193b9bb3454bef4b7b6f64a27de601/datasetproperties.py#L66
To:
```
K = K[~torch.isinf(K) & ~torch.isnan(K)]
```
Then it works.

**Comment by nickk124** [comment]
Hey, thanks for the fix! I was unaware of this bug; it's fixed now in 2e7e097823facf036ed6e766cfd663353a1975a7. I'll close this now but happy to reopen if you have any further issues.
